# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReadAskChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadAskChat
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenterReactNativeShared', '~> 1.0.1'



  platform :ios, '9.0'
  target 'ReadAskChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReadAskChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadAskChat-tvOS

  target 'ReadAskChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end